import 'package:flutter/material.dart';
import 'package:flutter_application_lectine_pal/widgets/itemcard.dart';
import 'package:flutter_application_lectine_pal/widgets/listheader.dart';

enum Category { vegetables, fruits, grains, nuts, oils, starch, dairy }

enum Type { lectine, lesslectine }

final List<Widget> itemCardsList = [
  const ListHeader(title: 'Gemüse'),
  ItemCard(
    title: 'Lektinhaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/anna-pelzer-IGfIGP5ONV0-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.vegetables.name,
    description: 'Gemüse',
  ),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/anna-pelzer-IGfIGP5ONV0-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.vegetables.name,
    description: 'Gemüse',
  ),
  ItemCard(
    title: 'Oxalathaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/louis-hansel-aKkfva3IdTw-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.vegetables.name,
    description: 'Gemüse',
  ),
  const ListHeader(title: 'Getreide'),
  ItemCard(
    title: 'Lektinhaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/mockup-graphics-XCSlkD0KNkk-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.grains.name,
    description: 'Getreide',
  ),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/mockup-graphics-XCSlkD0KNkk-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.grains.name,
    description: 'Getreide',
  ),
  const ListHeader(title: 'Obst'),
  ItemCard(
    title: 'Lektinhaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/naveed-pervaiz-IlnF2g_3tpY-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.fruits.name,
    description: 'Obst',
  ),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/naveed-pervaiz-IlnF2g_3tpY-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.fruits.name,
    description: 'Obst',
  ),
  const ListHeader(title: 'Nüsse & Samen'),
  ItemCard(
    title: 'Lektinhaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/maddi-bazzocco-UhrHTmVBzzE-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.nuts.name,
    description: 'Nüsse & Samen',
  ),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/maddi-bazzocco-UhrHTmVBzzE-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.nuts.name,
    description: 'Nüsse & Samen',
  ),
  const ListHeader(title: 'Öle'),
  ItemCard(
    title: 'Lektinhaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/roberta-sorge-uOBApnN_K7w-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.oils.name,
    description: 'Öle',
  ),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/roberta-sorge-uOBApnN_K7w-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.oils.name,
    description: 'Öle',
  ),
  const ListHeader(title: 'Milchprodukte'),
  ItemCard(
    title: 'Lektinhaltig',
    color: Colors.redAccent,
    imageAsset: 'assets/images/anita-jankovic-c7PT4PZMcNA-unsplash.jpg',
    type: Type.lectine.name,
    category: Category.dairy.name,
    description: 'Milchprodukte',
  ),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/anita-jankovic-c7PT4PZMcNA-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.dairy.name,
    description: 'Milchprodukte',
  ),
  const ListHeader(title: 'Stärke'),
  ItemCard(
    title: 'Lektinarm',
    color: Colors.greenAccent,
    imageAsset: 'assets/images/pesce-huang-pGJBkuqN27k-unsplash.jpg',
    type: Type.lesslectine.name,
    category: Category.starch.name,
    description: 'Stärke',
  ),
];
